version: '3.8'

services:
  oracle-db:
    image: container-registry.oracle.com/database/express:23.5.0.0-xfree
    container_name: javacunas-oracle
    environment:
      - ORACLE_PWD=OraclePassword123
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./docker/oracle/init:/opt/oracle/scripts/startup
    shm_size: 1gb
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/OraclePassword123@//localhost:1521/XEPDB1 as sysdba", "@healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    networks:
      - javacunas-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: javacunas-backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=JAVACUNAS
      - SPRING_DATASOURCE_PASSWORD=JavaCunas123
      - JWT_SECRET=YourSuperSecretJWTKeyChangeThisInProduction
    ports:
      - "8080:8080"
    depends_on:
      oracle-db:
        condition: service_healthy
    networks:
      - javacunas-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: javacunas-frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:8080/api/v1
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - javacunas-network
    restart: unless-stopped

volumes:
  oracle-data:
    driver: local

networks:
  javacunas-network:
    driver: bridge
