name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please fill out the form below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Backend (Spring Boot/Java)
        - Frontend (React/TypeScript)
        - Database (Oracle)
        - Infrastructure (Docker/Podman)
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (system unusable)
        - High (major feature broken)
        - Medium (feature partially broken)
        - Low (minor issue)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide details about your environment.
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, Windows 11, macOS 13]
        - Java Version: [e.g., OpenJDK 17.0.8]
        - Node Version: [e.g., 18.17.0]
        - Browser: [e.g., Chrome 115, Firefox 116]
        - Database Version: [e.g., Oracle 23c XE]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Include any relevant log output, error messages, or stack traces.
      render: shell
      placeholder: Paste logs here...

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem.
      placeholder: Drag and drop images here or paste URLs...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting.
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I am using the latest version of JavaVacunas
          required: true
        - label: I have provided all requested information
          required: true
