-- Create users table for medical staff and parents
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    role VARCHAR2(20) NOT NULL,
    license_number VARCHAR2(50),
    is_active CHAR(1) DEFAULT 'Y' NOT NULL,
    last_login TIMESTAMP,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_users_role CHECK (role IN ('DOCTOR', 'NURSE', 'PARENT')),
    CONSTRAINT chk_users_is_active CHECK (is_active IN ('Y', 'N'))
);

-- Create index for faster lookups
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_role ON users(role);

-- Add comment
COMMENT ON TABLE users IS 'Stores user information for medical staff and parents/guardians';
