-- Create children table
CREATE TABLE children (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    document_number VARCHAR2(20) UNIQUE NOT NULL,
    date_of_birth DATE NOT NULL,
    gender CHAR(1) NOT NULL,
    blood_type VARCHAR2(10),
    birth_weight NUMBER(5,2),
    birth_height NUMBER(5,2),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT chk_children_gender CHECK (gender IN ('M', 'F', 'O')),
    CONSTRAINT chk_children_birth_date CHECK (date_of_birth <= SYSDATE)
);

-- Create guardians table
CREATE TABLE guardians (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    document_number VARCHAR2(20) UNIQUE NOT NULL,
    phone VARCHAR2(20) NOT NULL,
    email VARCHAR2(100),
    address VARCHAR2(255),
    relationship VARCHAR2(50) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_guardians_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Create many-to-many relationship table
CREATE TABLE child_guardians (
    child_id NUMBER NOT NULL,
    guardian_id NUMBER NOT NULL,
    is_primary CHAR(1) DEFAULT 'N' NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_child_guardians PRIMARY KEY (child_id, guardian_id),
    CONSTRAINT fk_cg_child FOREIGN KEY (child_id) REFERENCES children(id) ON DELETE CASCADE,
    CONSTRAINT fk_cg_guardian FOREIGN KEY (guardian_id) REFERENCES guardians(id) ON DELETE CASCADE,
    CONSTRAINT chk_cg_is_primary CHECK (is_primary IN ('Y', 'N'))
);

-- Indexes for performance
CREATE INDEX idx_children_dob ON children(date_of_birth);
CREATE INDEX idx_children_document ON children(document_number);
CREATE INDEX idx_children_deleted ON children(deleted_at);
CREATE INDEX idx_guardians_document ON guardians(document_number);
CREATE INDEX idx_guardians_user ON guardians(user_id);

-- Comments
COMMENT ON TABLE children IS 'Stores children/infant records';
COMMENT ON TABLE guardians IS 'Stores guardian/parent information';
COMMENT ON TABLE child_guardians IS 'Links children with their guardians';
