-- Create vaccines table
CREATE TABLE vaccines (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    description VARCHAR2(500),
    manufacturer VARCHAR2(100),
    disease_prevented VARCHAR2(255) NOT NULL,
    dose_count NUMBER DEFAULT 1 NOT NULL,
    minimum_age_months NUMBER,
    storage_temperature_min NUMBER(4,1),
    storage_temperature_max NUMBER(4,1),
    is_active CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_vaccines_is_active CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT chk_vaccines_dose_count CHECK (dose_count > 0)
);

-- Create vaccination schedules table (PAI - Paraguay)
CREATE TABLE vaccination_schedules (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vaccine_id NUMBER NOT NULL,
    country_code CHAR(2) DEFAULT 'PY' NOT NULL,
    dose_number NUMBER NOT NULL,
    recommended_age_months NUMBER NOT NULL,
    age_range_start_months NUMBER,
    age_range_end_months NUMBER,
    is_mandatory CHAR(1) DEFAULT 'Y' NOT NULL,
    notes VARCHAR2(500),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_vs_vaccine FOREIGN KEY (vaccine_id) REFERENCES vaccines(id) ON DELETE CASCADE,
    CONSTRAINT chk_vs_is_mandatory CHECK (is_mandatory IN ('Y', 'N')),
    CONSTRAINT chk_vs_dose_number CHECK (dose_number > 0),
    CONSTRAINT chk_vs_age_range CHECK (age_range_end_months IS NULL OR age_range_end_months >= age_range_start_months)
);

-- Indexes
CREATE INDEX idx_vaccines_name ON vaccines(name);
CREATE INDEX idx_vaccines_active ON vaccines(is_active);
CREATE INDEX idx_vs_vaccine ON vaccination_schedules(vaccine_id);
CREATE INDEX idx_vs_country ON vaccination_schedules(country_code);
CREATE INDEX idx_vs_age ON vaccination_schedules(recommended_age_months);

-- Comments
COMMENT ON TABLE vaccines IS 'Master data for vaccines';
COMMENT ON TABLE vaccination_schedules IS 'Official vaccination schedules by country (PAI for Paraguay)';
