-- Create vaccination records table
CREATE TABLE vaccination_records (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_id NUMBER NOT NULL,
    vaccine_id NUMBER NOT NULL,
    schedule_id NUMBER,
    dose_number NUMBER NOT NULL,
    administration_date DATE NOT NULL,
    batch_number VARCHAR2(50) NOT NULL,
    expiration_date DATE NOT NULL,
    administered_by NUMBER NOT NULL,
    administration_site VARCHAR2(50),
    notes VARCHAR2(500),
    next_dose_date DATE,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_vr_child FOREIGN KEY (child_id) REFERENCES children(id) ON DELETE CASCADE,
    CONSTRAINT fk_vr_vaccine FOREIGN KEY (vaccine_id) REFERENCES vaccines(id),
    CONSTRAINT fk_vr_schedule FOREIGN KEY (schedule_id) REFERENCES vaccination_schedules(id),
    CONSTRAINT fk_vr_user FOREIGN KEY (administered_by) REFERENCES users(id),
    CONSTRAINT chk_vr_expiration CHECK (expiration_date >= administration_date),
    CONSTRAINT chk_vr_dose_number CHECK (dose_number > 0)
);

-- Indexes for performance
CREATE INDEX idx_vr_child ON vaccination_records(child_id);
CREATE INDEX idx_vr_vaccine ON vaccination_records(vaccine_id);
CREATE INDEX idx_vr_date ON vaccination_records(administration_date);
CREATE INDEX idx_vr_administered_by ON vaccination_records(administered_by);
CREATE INDEX idx_vr_next_dose ON vaccination_records(next_dose_date);

-- Comments
COMMENT ON TABLE vaccination_records IS 'Records of actual vaccine administrations';
