-- Create appointments table
CREATE TABLE appointments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_id NUMBER NOT NULL,
    appointment_date TIMESTAMP NOT NULL,
    appointment_type VARCHAR2(50) NOT NULL,
    status VARCHAR2(20) DEFAULT 'SCHEDULED' NOT NULL,
    scheduled_vaccines VARCHAR2(500),
    assigned_to NUMBER,
    notes VARCHAR2(500),
    created_by NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_apt_child FOREIGN KEY (child_id) REFERENCES children(id) ON DELETE CASCADE,
    CONSTRAINT fk_apt_assigned FOREIGN KEY (assigned_to) REFERENCES users(id),
    CONSTRAINT fk_apt_created FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT chk_apt_status CHECK (status IN ('SCHEDULED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'NO_SHOW'))
);

-- Indexes
CREATE INDEX idx_apt_date ON appointments(appointment_date);
CREATE INDEX idx_apt_child ON appointments(child_id);
CREATE INDEX idx_apt_status ON appointments(status);
CREATE INDEX idx_apt_assigned ON appointments(assigned_to);
CREATE INDEX idx_apt_created ON appointments(created_by);

-- Comments
COMMENT ON TABLE appointments IS 'Vaccination appointments scheduling';
