-- Create vaccine inventory table
CREATE TABLE vaccine_inventory (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vaccine_id NUMBER NOT NULL,
    batch_number VARCHAR2(50) NOT NULL,
    quantity NUMBER NOT NULL,
    manufacture_date DATE NOT NULL,
    expiration_date DATE NOT NULL,
    storage_location VARCHAR2(100),
    status VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL,
    received_date DATE DEFAULT SYSDATE NOT NULL,
    received_by NUMBER NOT NULL,
    notes VARCHAR2(500),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_vi_vaccine FOREIGN KEY (vaccine_id) REFERENCES vaccines(id),
    CONSTRAINT fk_vi_received_by FOREIGN KEY (received_by) REFERENCES users(id),
    CONSTRAINT chk_vi_quantity CHECK (quantity >= 0),
    CONSTRAINT chk_vi_status CHECK (status IN ('AVAILABLE', 'RESERVED', 'DEPLETED', 'EXPIRED', 'RECALLED')),
    CONSTRAINT chk_vi_dates CHECK (expiration_date > manufacture_date),
    CONSTRAINT uq_vi_vaccine_batch UNIQUE (vaccine_id, batch_number)
);

-- Indexes
CREATE INDEX idx_vi_vaccine ON vaccine_inventory(vaccine_id);
CREATE INDEX idx_vi_batch ON vaccine_inventory(batch_number);
CREATE INDEX idx_vi_expiration ON vaccine_inventory(expiration_date);
CREATE INDEX idx_vi_status ON vaccine_inventory(status);

-- Comments
COMMENT ON TABLE vaccine_inventory IS 'Vaccine inventory management with batch tracking';
