-- Create audit log table
CREATE TABLE audit_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR2(50) NOT NULL,
    operation VARCHAR2(10) NOT NULL,
    record_id NUMBER NOT NULL,
    user_id NUMBER,
    timestamp TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    old_values CLOB,
    new_values CLOB,
    CONSTRAINT chk_al_operation CHECK (operation IN ('INSERT', 'UPDATE', 'DELETE'))
);

-- Create notifications table
CREATE TABLE notifications (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id NUMBER NOT NULL,
    recipient_type VARCHAR2(20) NOT NULL,
    type VARCHAR2(50) NOT NULL,
    title VARCHAR2(200) NOT NULL,
    message VARCHAR2(1000) NOT NULL,
    reference_id NUMBER,
    reference_type VARCHAR2(50),
    is_read CHAR(1) DEFAULT 'N' NOT NULL,
    sent_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    read_at TIMESTAMP,
    CONSTRAINT chk_notif_recipient_type CHECK (recipient_type IN ('USER', 'GUARDIAN')),
    CONSTRAINT chk_notif_is_read CHECK (is_read IN ('Y', 'N')),
    CONSTRAINT chk_notif_type CHECK (type IN ('REMINDER', 'ALERT', 'INFO', 'WARNING'))
);

-- Indexes
CREATE INDEX idx_al_table ON audit_log(table_name);
CREATE INDEX idx_al_timestamp ON audit_log(timestamp);
CREATE INDEX idx_al_user ON audit_log(user_id);
CREATE INDEX idx_notif_recipient ON notifications(recipient_id, recipient_type);
CREATE INDEX idx_notif_is_read ON notifications(is_read);
CREATE INDEX idx_notif_sent ON notifications(sent_at);

-- Comments
COMMENT ON TABLE audit_log IS 'Immutable audit trail using Oracle blockchain table';
COMMENT ON TABLE notifications IS 'System notifications for users and guardians';
