-- Create application user and grant necessary privileges
ALTER SESSION SET CONTAINER = XEPDB1;

-- Drop user if exists (for clean re-initialization)
DECLARE
  v_user_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_user_count FROM dba_users WHERE username = 'JAVACUNAS';
  IF v_user_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP USER JAVACUNAS CASCADE';
  END IF;
END;
/

-- Create the user
CREATE USER JAVACUNAS IDENTIFIED BY JavaCunas123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

-- Grant necessary privileges
GRANT CREATE SESSION TO JAVACUNAS;
GRANT CREATE TABLE TO JAVACUNAS;
GRANT CREATE VIEW TO JAVACUNAS;
GRANT CREATE SEQUENCE TO JAVACUNAS;
GRANT CREATE PROCEDURE TO JAVACUNAS;
GRANT CREATE TRIGGER TO JAVACUNAS;
GRANT CREATE TYPE TO JAVACUNAS;
GRANT CREATE SYNONYM TO JAVACUNAS;
GRANT CREATE INDEX TO JAVACUNAS;
GRANT ALTER ANY TABLE TO JAVACUNAS;
GRANT COMMENT ANY TABLE TO JAVACUNAS;
GRANT SELECT ANY TABLE TO JAVACUNAS;

-- Commit the changes
COMMIT;

EXIT;
