-- Create application user and grant necessary privileges
ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER JAVACUNAS IDENTIFIED BY JavaCunas123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO JAVACUNAS;
GRANT CREATE TABLE TO JAVACUNAS;
GRANT CREATE VIEW TO JAVACUNAS;
GRANT CREATE SEQUENCE TO JAVACUNAS;
GRANT CREATE PROCEDURE TO JAVACUNAS;
GRANT CREATE TRIGGER TO JAVACUNAS;
GRANT CREATE TYPE TO JAVACUNAS;
GRANT CREATE SYNONYM TO JAVACUNAS;

EXIT;
